#ifndef SCREEN4VIEW_HPP
#define SCREEN4VIEW_HPP

#include <gui_generated/screen4_screen/Screen4ViewBase.hpp>
#include <gui/screen4_screen/Screen4Presenter.hpp>

class Screen4View : public Screen4ViewBase
{
public:
    Screen4View();
    virtual ~Screen4View() {}
    virtual void setupScreen();
    virtual void tearDownScreen();
    virtual void handleTickEvent();

    // 1. Virtual button actions generated by TouchGFX Designer
    virtual void btnMinusClicked();
    virtual void btnPlusClicked();
    virtual void btnConfirmClicked(); 

protected:
    // 2. Active temperature tracking variable (0 to 15)
    int16_t currentTemperature;

    // 3. RAM text buffers to feed  text wildcards dynamically
    Unicode::UnicodeChar tempTextBuffer[10];
    Unicode::UnicodeChar statusTextBuffer[20];

    // 4. Internal logic engine to update colors and status words based on temperature
    void updateTemperatureUI();
};

#endif // SCREEN4VIEW_HPP