#ifndef ALARMMESSAGETEMPLATE_HPP
#define ALARMMESSAGETEMPLATE_HPP

#include <gui_generated/containers/AlarmMessageTemplateBase.hpp>


class AlarmMessageTemplate : public AlarmMessageTemplateBase
{
public:
    AlarmMessageTemplate();
    virtual ~AlarmMessageTemplate() {}

    virtual void initialize();

    void setupAlarmCard(const char* titleStr, const char* descStr, touchgfx::colortype stripeColor);
    
    void setID(int id) { cardID = id; }
    int getID() const { return cardID; }

    // Overriding the virtual functions generated by TouchGFX Designer
    virtual void acknowledgeClicked();
    virtual void silenceClicked();

private:
    int cardID; 
    touchgfx::Unicode::UnicodeChar titleBuffer[32];
    touchgfx::Unicode::UnicodeChar descBuffer[128];
};

#endif // ALARMMESSAGETEMPLATE_HPP